version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: echo 1 # ここにあなたのプロジェクトにあわせたテストを記述
  deploy:
    working_directory: ~/app
    docker:
      - image: google/cloud-sdk:217.0.0-alpine
    steps:
      - checkout
      - run: apk add --no-cache nodejs npm yarn
      - run: yarn
      - run: yarn build
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud app deploy --quiet --project studio-andy-222018

workflows:
  version: 2
  main:
    jobs:
      #      - build # プロジェクトにあわせたテストを記述した場合はここのコメントアウトを外す
      - deploy:
          filters:
            branches:
              only: master
