version: 2

jobs:
  test:
    docker:
      - image: node:10.13.0
    working_directory: /repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Build
          command: yarn run build
      - persist_to_workspace:
          root: /repo
          paths:
            - ./node_modules
            - ./.nuxt
            - ./src/static/sw.js

  deploy:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: /repo
    steps:
      - checkout
      - attach_workspace:
          at: /repo
      - run:
          name: Decode credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ./secret.json
            echo $SECRET_YAML | base64 -d > ./secret.yaml
      - run:
          name: Deploy
          command: |
            gcloud auth activate-service-account --key-file=./secret.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            cd packages/studio-andy-app
            GOOGLE_APPLICATION_CREDENTIALS=./secret.json gcloud app deploy --quiet
      - run:
          name: Clean up
          command: rm ./secret.json

workflows:
  version: 2
  standard-workflow:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
